import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import LeftSlider from "@/components/Leftslider";
import RightSider from "@/components/RightSider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (


<html lang="en">
<ClerkProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <div className="h-fit flex justify-between ">
       <div className=" ">
  <RightSider  />
</div>
<div className="">
{children}
</div>

<div className="bg-blue-700  w-[24rem]">
  <LeftSlider/>
</div>

</div>
      </body>
      
</ClerkProvider>
    </html>


);

}
